### ISSUE TITLE
This is not whatsapp.

### ISSUE THREAD

**Issue by Kamleshcoderr** [marianif/whatsapp-clone#1]
You build only one page without backend.

**Comment by marianif** [comment]
I'm still building it as a portfolio project, don't know what is your point dude

**Comment by Kamleshcoderr** [comment]
Ok dear, but  your title  is whatsapp clone that's why I am saying it is not complete.only one page is completed.

**Comment by marianif** [comment]
Because the end project is a whatsapp clone leveraging amplify. Next time read the commits, there are just two of them: the initial commit and another one called "setup navigation" the state of the project is pretty clear.

**Comment by Kamleshcoderr** [comment]
Okay Dear, May I Contribute in this project..?
